### ISSUE TITLE
Replace tabs with spaces.

### ISSUE THREAD

**Issue by fwenzel** [x-tag/x-tag#28]
https://github.com/mozilla/webdev-bootcamp/blob/master/js-style.rst
https://twitter.com/BrendanEich/status/214570379497308160

'nuff said :)

**Comment by jlongster** [comment]
+1 for this. I know tabs are theoretically better, but practically they just cause problems, and editors handle all the tabbing/backspacing anyway. Spaces are more friendly for everybody.

**Comment by seanmonstar** [comment]
Eich is crazy.

**Comment by tofumatt** [comment]
I just came here to agree with @fwenzel.

**Comment by csuwildcat** [comment]
When files use spaces, all people do is desperately try to tweak their editor to treat space like tabs, which I personally find hilarious - figure I'd do 'em one better and use the real McCoy ;)

**Comment by timw4mail** [comment]
:-1:

Spaces are such a pain to adjust. Tabs can be deleted by tab stop, but spaces must be deleted space by space.

**Comment by jlongster** [comment]
I don't know many people that try to make spaces treated like tabs. You just follow the coding convention for the project, 2 or 4 spaces, and that's that. There are a bunch of other style rules that you must follow as well (like where to put spaces and parentheses within the code).

**Comment by tofumatt** [comment]
Most editors make it a snap to use spaces for indentation, including vim, emacs, Sublime Text 2, BBEdit, and TextMate -- which alone covers a lot of web developers.

**Comment by fwenzel** [comment]
Yeah I have yet to encounter a developer who manually goes through the process of "oh, 4 indentation levels, I must press space 16 times now".

**Comment by csuwildcat** [comment]
I wrote this up when we started, should help clear things up: https://docs.google.com/document/d/17bvj1fxJ93MX8H3HOpPwYr3si2atAbQkxmsUSsGmRc8/edit

**Comment by csuwildcat** [comment]
Updated the link, first paste was broken: https://docs.google.com/document/d/17bvj1fxJ93MX8H3HOpPwYr3si2atAbQkxmsUSsGmRc8/edit

**Comment by ghost** [comment]
Taking this one

**Comment by ghost** [comment]
Started indentation fixes, let me know if I am on the right track and I will complete the rest :: https://github.com/mozilla/x-tag/pull/42

**Comment by yorickpeterse** [comment]
@ossreleasefeed I already addressed this in #30 so this might result in conflicts.

**Comment by ghost** [comment]
@YorickPeterse thanks for the heads up

**Comment by ghost** [comment]
Did not want to open a specific issue for this, perhaps one should but basically, how does one know which of the open issues are actively being worked on by someone and which one's are open for takers? Also, I might have missed it but, is there a document/wiki which states the goals and phases of the project?

**Comment by csuwildcat** [comment]
I'd like to take a moment to address this question: "Also, I might have missed it but, is there a document/wiki which states the goals and phases of the project?"

Consider the following:

Since initial release, we have had 90% of our "contributions" center around the style and color choices of the demo pages, and the whitespacing choice for the code. Now I'm not going to say these items are worthless or bad, but when we just put a style together a few weeks ago for the project, I see changing the style (which works just fine) as a super low priority.

Additionally, the two individuals who are actually checking in _functional_, _feature_ code that does something to _advance the polyfill/lib/custom tags_, prefer tabs to spaces. I am not inclined to degrade the work flow of the folks who are actually pushing the project forward for the sake of a pedantic code style opinions - am I way off here?

I don't mean to be a dick, honestly, but I was really hoping to see code that, you know, did something other than format other code, or change the font-family of the logo...

There are a few things that I thought would be obvious priorities, thought I accept that this assumption was probably only obvious to me since I was so deep in gears creating all this, sorry about that.

Here's some stuff that matters:
- Perf Testing: how fast are tags parsed? how long does inflation take? If so, are there obvious bottlenecks we can correct?
- Tag Creation: iOS and Android have a shit-ton of good elements/controls, we need a lot of them for the web, let's get to it.
- Best Practices & Tutorials: I have a doc I was going to post next week on best practices, but a tutorial would be nice, anyone game?

Those are just a few of the needle-pushing enhancements and helpers that will advance our position, I would like to center development effort on these sorts of things.

**Comment by ghost** [comment]
@csuwldcat Thank you for the feedback. The second point you mentioned i.e. "Tag Creation: iOS and Android have a shit-ton of good elements/controls, we need a lot of them for the web, let's get to it." - It would be awesome if we had a shared spreadsheet or wiki page, on Github or the Mozilla wiki, that lists the tags/widgets that is envisioned, which have been completed, which are currently being worked on and which is still open.

**Comment by csuwildcat** [comment]
@ossreleasefeed to that end, we have an intern producing our take on this design guide for Android so we have something equivalent for Web/Firefox OS apps: http://developer.android.com/design/index.html

She just pinged me today to let me know she is almost finished compiling the list of components that we will need for the foundation of our app design/UI ecosystem. As soon as I have that list in hand, work will begin immediately on the tags in the priority they are listed. This should be ready for consumption early next week, at which point we will really be pushing for contributions to make the list a reality.

Additionally, Arron and I have a brand spanking new Tag Registry that we have about 90% done, also due out early next week. This tag registry will let you easily (I mean s u p e r easily) get your tags registered and out to the word - think "NPM of custom tags", but with more sexiness and ergonomics.

I will publish the needed-tag list to the wiki as soon as I get it, we are days out from all of this! :)

**Comment by ghost** [comment]
@csuwldcat This is awesome, looking forward to it.

**Comment by pennyfx** [comment]
Spaces have won.  You can put away your pitch forks.

**Comment by fwenzel** [comment]
lol

/me puts away his pitch fork
