### ISSUE TITLE
Figure out a sane way to offer a DOMComponentsLoaded custom event

### ISSUE THREAD

**Issue by csuwildcat** [x-tag/x-tag#29]
People need to know when all the components in the static page source have "loaded". Figure out how to check for it and fire a custom event.

**Comment by csuwildcat** [comment]
Just landed on master: https://github.com/mozilla/x-tag/pull/37

**Comment by brettz9** [comment]
Since you are using "WebComponentsReady" to detect when to fire the event anyways, why not just have the user check for this event since it is an event at least also recognized by Polymer [unlike DOMComponentsLoaded](https://github.com/Polymer/CustomElements/search?q=DOMComponentsLoaded&type=Code)? (and apparently discussed as a candidate for standardization at least at http://lists.w3.org/Archives/Public/public-webapps/2013JulSep/0697.html ).

That being said, to my understanding, the [polymer-ready event](http://stackoverflow.com/a/21764109/271577) looks more like what your "WebComponentsReady" event is doing since in your case it is firing after the "created" lifecycle item.
