### ISSUE TITLE
IE8 support

### ISSUE THREAD

**Issue by molnarg** [x-tag/x-tag#40]
Will there be IE8 support? Is it possible to support IE8 at all?

IE8 support would be critical because it is the last supported IE on Windows XP as fas as I know.

**Comment by michaelkrog** [comment]
Hmm. Is it really Crucial?

According to global stat IE8 is at 13% worldwide and looses 0.5 - 1% each month. Windows XP users are 27.6% whichs shows that more than half the XP users around the world uses another browser than IE8 - maybe the other half should acknowledge that their OS is about to expire and the only thing they can could to prevent it right now is to install Google Chrome.

Considering the amount of effort to make old crappy browsers work IE8 might not be that crucial after all?

PS: I'm forced to use Windows XP myself at my workplace. :-(

**Comment by fwenzel** [comment]
"Hmm. Is it really Crucial?" I am with Michael on that. I don't think IE8 support is a great place to invest our resources. Mind you, I am not opposed to a solution that works for IE8 too, but if it was _officially supported_ that would mean we'd need to employ CSS tweaks etc to make the tags actually work _well_ in IE8. This is a considerable overhead for limited gain.

**Comment by csuwildcat** [comment]
Support for IE8 (and even IE6/7) is possible, but I do not want to pursue it in the production version of X-Tag. Making X-Tag work for older versions of IE requires the following:
- patch/polyfill all modern-browser DOM method used inside X-Tag (things like child/sibling references, querySelector, etc)
- polyfill or ditch all ES5 methods used inside X-Tag
- augment the keyframe style sheet detection to feature detect IE and use a CSS behavior rule instead of a CSS Animation Keyframe rule
- bundle or serve from a CND an .htc file that detects node insertion

After doing all those things, you would have support for IE8, and theoretically down to IE6 - I have tested a proof-of-concept in IE8 and I know this is viable, but the cost is too much considering the goal of X-Tag is to polyfill modern browsers.

I am happy to go into detail on the points above so others can fork the repo and employ these polyfill techniques, but at this point this is not a priority for us.

**Comment by molnarg** [comment]
Well, we are building a business application and we are looking for a component system to work with. But we are forced to support IE8 because, as a I said, a lot of companies are still stuck with Windows XP, and on XP, the latest supported IE is IE8. But I agree that it is not critical if you target another market with your app.

Considering what @csuwldcat said, this is probably not worth investing in IE support. Thanks for the investigation though.

**Comment by csuwildcat** [comment]
Oh btw, to add to the < IE9 cause, it should be noted that even jQuery 2.0 is dropping support for IE8 and below - I have a feeling this will make the transition away from legacy instantly do-able for the vast majority of developers ;)
