### ISSUE TITLE
Content overwrites all existing content for a tag

### ISSUE THREAD

**Issue by niftynei** [x-tag/x-tag#47]
Currently, setting the content property obliterates the current content for a given node.  Should give option to append instead of replace.

**Comment by csuwildcat** [comment]
The reason we went with a content option is because that is what is found in the W3 spec. I don't really want to add more sugar to the API and object definition - as an example of why: what happens when Joe Blow comes in and wants the same thing, but to have elements prepended instead?

Needless to say there is still an easy way to accomplish what you want: just inject the default tag content in the onCreate lifecycle function instead, you should have all the control you need from inside that function ;)

**Comment by niftynei** [comment]
Appending in onCreate is what I ended up doing.  Thanks for the hint :)
