### ISSUE TITLE
Why not use package.json and npm?

### ISSUE THREAD

**Issue by tristanz** [x-tag/x-tag#53]
Is there a reason why not to standardize on package.json instead of xtag.json?  I'm sure you've thought of this but reusing the NPM infrastructure seems like it would be a big win.

All it would require would be to add a custom xtag field.  This would give you all the great features of NPM (install, publish, upgrade, remove, etc) for free.  I understand that xtags are not Node specific, but leveraging package.json doesn't stop anybody from installing the xtag directly.  The Node community will also almost certainly wrap xtags into packages and publish them to npm as soon as somebody implements an express.js middleware that helps automatically load xtag dependencies.  That will ultimately fracture the xtags community.

**Comment by csuwildcat** [comment]
Because another program could already be using a package.json in their app,
and NPM is dreadful package search website in terms of features, discovery,
and full-text search capability (namely because such capability is
non-existent).

Additionally, we gain little from using NPM, as custom elements have zero
backend applicability, thus a command line is largely irrelevant. We have a
much easier "packaging" idea in mind that is featherweight and side steps
complexity (you won't even need to manage tag assets in your projects)

Any further questions or concerns?
On Jul 29, 2012 10:30 AM, "Tristan Zajonc" <
reply@reply.github.com>
wrote:

**Comment by tristanz** [comment]
That makes sense.  I'm eager to see the whole story gets fleshed out. xtags looks fantastic.
