### ISSUE TITLE
Get x-tag to work with RequireJS

### ISSUE THREAD

**Issue by jlubean** [x-tag/x-tag#71]
I would like to be able to use x-tag with RequireJS (http://requirejs.org/) where x-tag would be loaded asynchronously by RequireJS.

When I try to use x-tag this way, I find that the onCreate and onInsert registered functions **never** get invoked when I set the innerHTML of a container tag with the registered tag:

``` javascript
document.getElementById("content").innerHTML = '<mytag id="tag-1">Test</mytag>';
```

If I then set a value on the tag, the registered setter function **never** gets invoked:

``` javascript
document.getElementById("tag-1").myValue = "This is Tag 1";
```

The onCreate function **is** invoked when I create a new element:

``` javascript
var e = document.createElement("mytag");
```

But, the onInsert function **is not** invoked when I append the tag:

``` javascript
document.body.appendChild(e);
```

Here is my simple HTML file that loads RequireJS and tells it to load my main JavaScript file (test-require-xtag.js):

``` html
<!DOCTYPE html>
<body>
    <div id="content"></div>
    <script src="js/lib/require.js" data-main="js/test-require-xtag.js"></script>
</body>
</html>
```

Here is the test-require-xtag.js file:

``` javascript
require(['lib/x-tag'], function(xtag) {
    var createdCount = 0, insertedCount = 0, testName = "Test require/x-tag";
    xtag.register('mytag', {
        onCreate: function(){
            // fired once at the time a component 
            // is initially created or parsed
            console.log(testName + ": created mytag (count: " + (++createdCount) + ")");
        },
        onInsert: function(){
            // fired each time a component 
            // is inserted into the DOM
            console.log("Test require/x-tag: inserted mytag (count: " + (++insertedCount) + ")");
        },
        events: {
        },
        getters: {
        },
        setters: {
            myValue: function(value) {
                this.dataset.myValue = value;
                console.log(testName + ": myValue was set on mytag (id="+this.id + ")");
            }
        },
        methods: {
        }
    });

    console.log(testName + ": registered mytag");
    console.log(testName + ": about to set innerHTML on div")
    document.getElementById("content").innerHTML = '<mytag id="tag-1">' + testName + '</mytag>';
    console.log(testName + ": about to set myValue attribute on id=tag-1");
    document.getElementById("tag-1").myValue = "This is Tag 1";
    console.log(testName + ": about to create second mytag");
    var e = document.createElement("mytag");
    e.id = "tag-2";
    console.log(testName + ": about to set myValue attribute on id=tag-2");
    e.myValue = "A value";
    console.log(testName + ": about to append second mytag");
    document.body.appendChild(e);

});
```

**Comment by geddski** [comment]
+1 this is a deal-breaker for everyone using async loading.

**Comment by csuwildcat** [comment]
The issue is that the tags are recognized by their inflation in the DOM. Setting innerHTML will work, if you do it in the DOM. Outside the DOM, there is not a sane way of detecting innerHTML inflation (you can get the native setter and wrap that in Firefox but other browsers like Safari (iPhone/Desktop) don't support it).

There are two options:
1. offer an element method called "inflateElements" (HTMLElement.prototype.inflateElements) which you can run to ensure the tags are set in this off-DOM use-case.
2. be sure to always set your element innerHTML after DOM insertion

Thoughts?

PS - the standard W3 method, document.register(), accounts for this (they have access to the element creation phases content code running in pages does not, obviously). When it lands in Firefox, we will wrap and use it in X-Tag internally, until we'll need to decide on one of the above mentioned solutions (or another you have an ideas on?)

**Comment by pennyfx** [comment]
@jlubean I think the real issue here is that you are loading it async and 'DOMContentLoaded' has already fired.  Previously, X-Tag depended on that event to initialize itself. However, I added a patch the other day that addressed this issue.   Here https://github.com/mozilla/x-tag/commit/7c571cafcd68c928f1ce21125b47d7dabde876fe

Can you verify that you have latest from master?

**Comment by jlubean** [comment]
I verified that I have the latest x-tag.js from master and that the example code I provided above still produces the same results.  The RequireJS library ensures that the x-tag.js file is loaded/executed prior to executing my anonymous callback that invokes xtag.register()

**Comment by pennyfx** [comment]
@jlubean Get latest.  I just added a few tests for AMD and found that we needed to check for readyState == 'interactive' when initializing the library.  Everything should work now.

**Comment by jlubean** [comment]
@pennyfx Everything worked except for the setter function was not invoked on the mytag after it was added by setting innerHTML:

``` javascript
document.getElementById("content").innerHTML = '<mytag id="tag-1">' + testName + '</mytag>'; //This invokes onCreate and onInsert
document.getElementById("tag-1").myValue = "This is Tag 1";  //This should invoke the setter function
```

The onCreate and onInsert functions were invoked, but the "myValue" setter function was not invoked.

**Comment by geddski** [comment]
getting closer...

**Comment by pennyfx** [comment]
@jlubean We added a new method called xtag.innerHTML(elem, html) to work around this issue.  

The problem is that we are using element observers to detect changes in the DOM and these observers run in a 'microtask' which are asynchronous.  This means that when you set innerHTML it takes a short amount of time for the observer to report the changes back to x-tag and allow x-tag to inflate your newly inserted x-tag.  You can test this by wrapping all your code after `elem.innerHTML = '<mytag></mytag>'` in a `setTimeout(fn,1);` and you will see how everything works.

So our only solution is to provide a helper method to get around this issue.   xtag.innerHTML() method allows us to inflate the xtags inside of innerHTML in a synchronous manner so you can immediately start working with your xtag elements in the next line of code.   Give it a try and let us know what you think.

**Comment by jlubean** [comment]
@pennyfx Nice work-around.  I noticed that the latest code now causes the onInsert function to be invoked twice when elem.innerHTML is set directly or when the xtag.innerHTML() function is used.

**Comment by pennyfx** [comment]
@jsocol Ok, we fixed the bug that was causing onInsert to be called twice.

**Comment by jsocol** [comment]
ITYM @jlubean FTFY. But good! :+1:

**Comment by jlubean** [comment]
@pennyfx I verified that it works.  Thanks for the quick response/turnaround!  You rock!
