### ISSUE TITLE
Multiple elements defined with shorthand in the same parent don't fire onInsert

### ISSUE THREAD

**Issue by avaly** [x-tag/x-tag#73]
It seems that `if (doc.documentElement.contains(element)){` in the `nodeInserted` function returns false for elements within the same parent if they are defined with the `/>` shorthand.

Only the first button will be fired an onInsert event, while the second button won't have it fired.

``` html
<div>
    <ui-button title="First"/>
    <ui-button title="Second"/>
</div>
```

Reproducible in Firefox 16 & Chrome 22, but not on IE 9, on Windows 7.

These cases work as expected:

``` html
<div>
    <ui-button title="First"/>
</div>
<div>
    <ui-button title="Second"/>
</div>
```

``` html
<div>
    <ui-button title="First"></ui-button>
    <ui-button title="Second"></ui-button>
</div>
```

**Comment by csuwildcat** [comment]
The DOM API contains() is a standard browser method, not something we
added. If this is an issue with its operation, it would be either a bug in
Firefox or the spec for the standard.

What I believe is happening though, is that while the browser may render
your self-closed custom tag, the contains() API does not account for them
because non-native self-closing tags aren't valid HTML (to my knowledge).

Additionally, X-Tag will likely be landing a patch soon that enforces the
"x-" prefix requirement, as described in the standard W3 API.

**Comment by avaly** [comment]
You are right, the self-closing tags aren't valid HTML tags and that's why the DOM API behaves this way.

Would be a good idea, to make this note in the documentation, so others don't fall down this path.
